plugins:
  available_interface_locales:
    default: 'ar|bs_BA|ca|cs|da|de|el|en|es|et|fa_IR|fi|fr|gl|he|id|it|ja|ko|lv|nb_NO|nl|pl_PL|pt|pt_BR|ro|ru|sk|sl|sq|sr|sv|te|th|tr_TR|uk|ur|vi|zh_CN|zh_TW'
    choices: 'LocaleSiteSetting.supported_locales'
    type: list
    client: false
